CC = gcc
CFLAGS = -Wall -Wextra -pthread
LDFLAGS = -lrt

all: server client

server: server.c
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

client: client.c
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

clean:
	rm -f server client
